require_relative 'circumcircle'
require_relative 'draw'
require_relative 'vec2d'
require_relative 'vector'
require_relative 'polygon'
require_relative 'polygon_factory'
require_relative 'triangle'
require_relative 'triangulation'
require_relative 'mesh'
require_relative 'line'
require_relative 'ray'
require_relative 'segment'
EPSILON = 1e-7
